CREATE SCHEMA IF NOT EXISTS schema1;
CREATE TABLE IF NOT EXISTS schema1.table1 (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE SCHEMA IF NOT EXISTS schema2;
CREATE TABLE IF NOT EXISTS schema2.table1 (
    id SERIAL PRIMARY KEY,
    name TEXT
);
